apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - provider.yaml
  - providerconfig.yaml
  - database-xrd.yaml
  - database-composition.yaml
  - database-claim.yaml
  - storage-claim.yaml
